### ISSUE TITLE
node v4 switch

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#190]
## Pros:
- less dependencies (no babel runtime, no promise lib)
- faster testing (faster runtime, less travis configurations)
- less compilation: native ES6, native Promises, async funcs to generators, readable code
- faster (in theory)
## Cons:

:question:  Let's discuss \cc everyone
## TODOs:
- [x] Disable following babel transpillers according to https://nodejs.org/en/docs/es6/#which-es6-features-ship-with-node-js-by-default-no-runtime-flag-required

```
 "es6.arrowFunctions",
    "es6.classes",
    "es6.properties.computed",
    "es6.properties.shorthand",
    "es6.constants",
    "es6.blockScoping",
    "es6.templateLiterals",
    "regenerator",
    "runtime",
    "es7.asyncFunctions"
```
- [x] Transpile `async` funcs to generators: https://babeljs.io/docs/advanced/transformers/other/async-to-generator/
- [x] Remove `es6-promise` and `babel-runtime` from deps
- [x] Rewrite tests with supported ES6 syntax
- [x] Reconfigure travis to run only `node stable`

**The first step overs here.**
- [x] After that we need to get stats from health monitor.
- [x] Then we should try to remove `yakka` dependency and try native http agent. Node 10 shipped with broken keep alive. It should be fixed now. If it's not, health monitor will show us signficant performance regression (~x1.5-x2).

**Comment by miherlosev** [comment]
I think we should take into account this - https://github.com/nodejs/LTS.
We can switch to version 4.0 when LongTerm support for 0.12 version is finished - 2017-04-01.

**Comment by inikulin** [comment]
@miherlosev good point

**Comment by miherlosev** [comment]
I'm woking on this
